variable "storage_access_key" {
  description = "Access Key ID generated by the google_storage_bucket module"
  type        = string
}

variable "storage_secret" {
  description = "Secret Access Key generated by the google_storage_bucket module"
  type        = string
}

variable "smtp_login" {
  description = "SMTP server login username"
  type        = string
}

variable "smtp_password" {
  description = "SMTP server password"
  type        = string
}

variable "redis_password" {
  description = "Redis server password"
  type        = string
}

variable "otp_secret" {
  description = "OTP Secret (generate with: docker run -it tootsuite/mastodon:latest bundle exec rake secret)"
  type        = string
}

variable "secret_key_base" {
  description = "Base Secret Key (generate with: docker run -it tootsuite/mastodon:latest bundle exec rake secret)"
  type        = string
}

variable "vapid_private_key" {
  description = "Vapid Private Key (generate with: docker run -it tootsuite/mastodon:latest bundle exec rake mastodon:webpush:generate_vapid_key)"
  type        = string
}

variable "vapid_public_key" {
  description = "Vapid Public Key (generate with: docker run -it tootsuite/mastodon:latest bundle exec rake mastodon:webpush:generate_vapid_key)"
  type        = string
}

variable "mastodon_postgres_secret" {
  description = "Postgres password (generate with: docker run -it tootsuite/mastodon:latest bundle exec rake secret)"
  type = string
}
